### ISSUE TITLE
Virtuoso 性能问题

### ISSUE THREAD

**Issue by zhutmost** [cihlab/fics-cluster-guide#1]
Virtuoso存在严重的性能问题，主要表现是操作延时。

Kun的初步判断是srun -x11对于Virtuoso存在性能瓶颈。
（具体内容请参考群里的讨论）

**Comment by zhutmost** [comment]
建议需要使用Virtuoso的老师同学，直接使用salloc

**Comment by llfl** [comment]
slurm 内置的x11转发性能有问题，社区其实已经有人提出过类似的问题，但目前为止没看到有相关社区解决方案https://lists.schedmd.com/pipermail/slurm-users/2019-October/004205.html。ilaunch改成远程x11直通，问题解决

**Comment by zhutmost** [comment]
// 广告插播：[zLaunch](https://github.com/cihlab/zlaunch) 一直就没有这个问题（我之前不知道是因为不会Virtuoso哈哈哈）
