### ISSUE TITLE
run_verdi排队时间过长

### ISSUE THREAD

**Issue by jingxi-chen** [cihlab/fics-cluster-guide#12]
老师您好，我通过ilaunch提交运行verdi的命令到boltzmann节点后，一直处于排队状态，已经持续了2小时了。
之前有时也会出现排队很久的情况。
更换到hopfield节点还是一直处于排队状态。
以下附squeue -p boltzmann;squeue -p hopfiled;sinfo命令的截图。
![image](https://github.com/cihlab/fics-cluster-guide/assets/143076516/a8b2d2ef-2290-4f2f-a299-35c52d20e1c2)
![image](https://github.com/cihlab/fics-cluster-guide/assets/143076516/38ce433e-006b-4004-86b4-59037ac0a99b)
![image](https://github.com/cihlab/fics-cluster-guide/assets/143076516/4bfb1f5c-eb23-4c56-be6a-cf9b3d304423)

**Comment by zhutmost** [comment]
我们注意到了这个现象，直接原因是现在用户有点多。

**Comment by jingxi-chen** [comment]
> 我们注意到了这个现象，直接原因是现在用户有点多。

明白了，谢谢老师，现在正常了

**Comment by zhutmost** [comment]
最近类似问题出现多么
