### ISSUE TITLE
希望管理员帮忙装几个新的EDA软件

### ISSUE THREAD

**Issue by Acat-Wang** [cihlab/fics-cluster-guide#13]
华大九天提供了一些新的软件，包括skipper，iwave和argus。希望管理员有空的时候帮忙安装一下，安装包我放在/capsule/share/acatwang/empyrean里面了，多谢！
![image](https://github.com/cihlab/fics-cluster-guide/assets/46415662/ef824d43-96aa-46e4-aa35-c1e1cd63cb36)

**Comment by Acat-Wang** [comment]
新增一个liberal，安装包路径相同。四月license我也丢里面了，麻烦管理员更新一下。
可以优先安装一下iwave，其他的倒是不急。
![image](https://github.com/cihlab/fics-cluster-guide/assets/46415662/cec6dcc2-c599-4de8-9e1e-9c95b85f2d42)

**Comment by llfl** [comment]
<img width="521" alt="image" src="https://github.com/cihlab/fics-cluster-guide/assets/10126413/c1ae01d1-159d-43c0-8c24-df7708cdb580">
done

**Comment by Acat-Wang** [comment]
我在mgmt01上用module avail指令可以看到这几个新装的eda，但miller上不行，只有原来的几个，请问是我的操作有问题吗
