### ISSUE TITLE
gvim 安装请求

### ISSUE THREAD

**Issue by YangcyXiang** [cihlab/fics-cluster-guide#15]
现有的 **vim** 不便于工作，希望能够在服务器上安装 **gvim**，方便使用，谢谢

![gvim](https://github.com/cihlab/fics-cluster-guide/assets/45559266/16eabed1-ecbf-4634-8247-dece5f80f7c3)

**Comment by zhutmost** [comment]
VIM/GVIM是支持remote ssh的，你可以在你的本机上安装VIM/GVIM，编辑服务器上的文件。可以考虑试试。

至于是否安装，请管理员Kun决定。

**Comment by YangcyXiang** [comment]
好滴，主要是后端人员说 vim 不方便操作，ssh 他们要上手可能也有一定的学习成本。自己用的话还好来着，vscode 就可以了。

**Comment by llfl** [comment]
gvim现在可以在knob自行安装
