### ISSUE TITLE
虚拟环境的一些小问题反馈

### ISSUE THREAD

**Issue by Acat-Wang** [cihlab/fics-cluster-guide#16]
1.capsule/share的读写权限没了，显示带锁，目前为只读状态。但permission看起来又没什么问题，很奇怪。
![image](https://github.com/cihlab/fics-cluster-guide/assets/46415662/5e8ded37-3265-453a-8c92-ccabe96d0db2)
![image](https://github.com/cihlab/fics-cluster-guide/assets/46415662/c291cd9c-be68-49d7-8ba5-3336160c2c85)
2.zshell下使用module avail命令读不到eda列表，也没法module load。不过切回cshell就行，这个对我倒也没啥影响。

另外有几个疑问：
1.虚拟环境是不是只要开着就会占用资源，不论是否有任务正在运行？
2.如果需要增加mem等资源，需要怎么操作？我试过 knob -c 16 -m 40000 start但提示“VNC Instance is now running, so do nothing“。先knob shutdown或者knob reset再start也不行，虽然不会报错，但进入vnc用lscpu命令发现还是8核心16G内存

**Comment by Acat-Wang** [comment]
好像有几个图没传上来，补充一下
![屏幕截图 2024-04-11 004255](https://github.com/cihlab/fics-cluster-guide/assets/46415662/e2a52b01-9721-4049-a3ef-b02ef14be7a3)
![屏幕截图 2024-04-11 010819](https://github.com/cihlab/fics-cluster-guide/assets/46415662/ad4fefdd-3aaf-48f3-bd04-52096b42612b)
![屏幕截图 2024-04-11 010854](https://github.com/cihlab/fics-cluster-guide/assets/46415662/60cdbabc-a2a1-45a7-a592-f9169368ecc6)

**Comment by llfl** [comment]
有配置cpu的选项不代表有权限配置，后面会加上反馈提示

**Comment by Acat-Wang** [comment]
knob reset之后，sudo yum 的权限好像没有了

**Comment by llfl** [comment]
reset是所有环境重置KUN在 2024年4月11日，15:19，Acat-Wang ***@***.***> 写道：﻿
knob reset之后，sudo yum 的权限好像没有了

**Comment by zhutmost** [comment]
1) 我这边PATH里没有gedit等一些软件
<img width="970" alt="image" src="https://github.com/cihlab/fics-cluster-guide/assets/20497382/373bfea2-004a-4729-bbbd-49bfb9da706b">
2) GUI里压缩包解压工具好像没设置上？即tar.gz压缩包右键没法extract

**Comment by llfl** [comment]
桌面gui至今没变过，看起来是设置的问题KUN在 2024年4月16日，22:16，Haozhe Zhu ***@***.***> 写道：﻿
另外，整个gui看上去之前相比 有点怪怪的（更加复古了），请问是有意为之么
image.png (view on web)

**Comment by zhutmost** [comment]
另外，我这边module av是空的，如果试图load我知道的任何东西的话cannot locate module files balabala。原因不详

**Comment by llfl** [comment]
可能是你虚拟环境的镜像版本比较低，重新reset一下会更小镜像KUN在 2024年4月16日，22:22，Haozhe Zhu ***@***.***> 写道：﻿
另外，我这边module av是空的，如果试图load我知道的任何东西的话cannot locate module files balabala。原因不详

**Comment by zhutmost** [comment]
> 可能是你虚拟环境的镜像版本比较低，重新reset一下会更小镜像KUN在 2024年4月16日，22:22，Haozhe Zhu ***@***.***> 写道：﻿ 另外，我这边module av是空的，如果试图load我知道的任何东西的话cannot locate module files balabala。原因不详 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

解决了

**Comment by Acat-Wang** [comment]
![image](https://github.com/cihlab/fics-cluster-guide/assets/46415662/1946f390-a06d-4551-8ab2-a3257fd24169)
knob reset了一下，然后就连不上网了

**Comment by llfl** [comment]
knob镜像基本稳定，有问题reset 更新至最新版本镜像即可
