### ISSUE TITLE
Lamport  无法正常访问

### ISSUE THREAD

**Issue by Zhirui-Huang** [cihlab/fics-cluster-guide#19]
- 从 mgmt 无法访问 lamport 或者等待时间较长
- 从 cloud-hopfielf/ makkapakka 可以正常访问lamport
- mgmt 无法访问 lamport 导致 vscode 连接服务器时无法访问lamport 内的conda 环境
![image](https://github.com/cihlab/fics-cluster-guide/assets/77948047/939cfae4-7fb0-4e02-a337-0271acd8e1b1)

**Comment by llfl** [comment]
最新版本的knob镜像有makkapakka
