### ISSUE TITLE
Failed to submit task to makkapakka01

### ISSUE THREAD

**Issue by lazh001** [cihlab/fics-cluster-guide#2]
Squeue shows makkapakka01 is idle. But when I submit a task, my task is queued and waiting for resources.
Here is the instruction submitting the task:
![a24c1fe165da30a91cc629ad41ae8a7](https://github.com/cihlab/fics-cluster-guide/assets/80265531/68ef95fb-cdad-4c19-bb3a-92a14a067d7e)
Here is the squeue result after I submitted my task:
![d384110684c6dbbe166fcb134c5f80c](https://github.com/cihlab/fics-cluster-guide/assets/80265531/64d794fa-a1e4-4f85-b628-49a9ce634fd3)

**Comment by zhutmost** [comment]
这个问题解决了么 @llfl 
解决了的话 可以close掉

**Comment by llfl** [comment]
gpu 没有5
