### ISSUE TITLE
ssh登录初始化失败

### ISSUE THREAD

**Issue by satreeby** [cihlab/fics-cluster-guide#22]
用户名：shuanyang
使用ssh登录，输入密码后，welcome也不显示了，一直卡在那，等了半天也没有反应
![problem](https://github.com/cihlab/fics-cluster-guide/assets/121990367/4a8c3a25-96e1-4be0-97ab-33edb705193d)
ctrl c 退出该进程后，跳转到页面
![image](https://github.com/cihlab/fics-cluster-guide/assets/121990367/18047eb6-ad9d-4603-b7f8-e359bbe39d03)
在该界面可以正常source .bashrc，结果为
![image](https://github.com/cihlab/fics-cluster-guide/assets/121990367/f82450bc-b36f-479e-8721-355c8313989c)

**Comment by llfl** [comment]
你干了什么？

**Comment by satreeby** [comment]
我也不知道我干了啥，但是我感觉我应该大概率啥也没干？因为周一还是能打印出来welcome的，但是那天我也就只是登陆了一下，然后啥也没干，周三登录的时候他就不行了

**Comment by llfl** [comment]
用knob可解
