### ISSUE TITLE
Metis打不开

### ISSUE THREAD

**Issue by Acat-Wang** [cihlab/fics-cluster-guide#25]
试图打开Metis的时候提示连不上license服务器。翟博能正常打开但我不行（翟博当我面打开，然后关闭，然后我再打开，还是提示连不上license服务器），后来我找姜皓试了一下也不行。指令和运行结果如下：
![image](https://github.com/cihlab/fics-cluster-guide/assets/46415662/4e72c49c-3741-4c4d-aef3-c3ea1ee4ecdb)
![image](https://github.com/cihlab/fics-cluster-guide/assets/46415662/bce08752-435c-48df-961b-e4d2ee873fef)

**Comment by Acat-Wang** [comment]
![image](https://github.com/cihlab/fics-cluster-guide/assets/46415662/3f8827c7-4ed8-493c-a98a-6c2f714e2ae5)

**Comment by llfl** [comment]
done

**Comment by llfl** [comment]
metis 现在的license所有的feature都只能是单人使用，之前有人的程序退出不完全，导致某些feature没有释放，现在重新启动license就好了
