### ISSUE TITLE
每次更新能不能发个通知啊

### ISSUE THREAD

**Issue by xiaoshou-zheng** [cihlab/fics-cluster-guide#26]
# 每次更新能不能发个通知啊
比如更新了什么功能或者修复了什么bug  
以及需不需要用户端手动reset或者什么一下才能用新功能之类的  
现在服务器全靠口耳相传才能用起来

**Comment by zhutmost** [comment]
因为目前没人专职写文档。之前让锥写，他也没写😶

**Comment by llfl** [comment]
1. 修复bug的话自行通过issue了解。不过当前大部份issue 问题解决的时确实没有给出明确结论（那是因为我懒得写，这个看心情😅），这个你有权在这些已关闭的issue上追问详情。2. 某些bug涉及到镜像更新，首先还是通过issue了解，其次knob reset会自动更新镜像，所以我理解是这样的：a. 如果你遇到问题，reset -> 问题解决；b. 如果没遇到问题 -> 说明你不受问题影响 -> 等下次真正遇到问题 reset -> 问题解决。所以这部分不应该有问题。3. 真的有功能更新，导致镜像更新，这部分确实需要通知，但是其实频率并不高（可以说频率极低，我也没这么多精力天天更新功能～）KUN在 2024年7月3日，15:28，Jiapei Zheng ***@***.***> 写道：﻿
每次更新能不能发个通知啊
比如更新了什么功能或者修复了什么bug
以及需不需要用户端手动reset或者什么一下才能用新功能之类的
现在服务器全靠口耳相传才能用起来
