### ISSUE TITLE
VNC连接失败，restart之后也无法连接

### ISSUE THREAD

**Issue by liyjbruce** [cihlab/fics-cluster-guide#27]
目前连接VNC遇到问题，连接不上。我的操作如下：
1，打开命令提示符窗口输入ssh -L 60000:cloud-liyj:5901 liyj@10.155.102.33 ，此时可以正常连接服务器。并查看KNOB状态显示running。
<img width="648" alt="image" src="https://github.com/cihlab/fics-cluster-guide/assets/142145515/6b04d937-ab22-40be-b68a-04c57ec1344a">
2，打开vnc输入 localhost:60000 回车，弹出如下窗口。
<img width="770" alt="vnc问题" src="https://github.com/cihlab/fics-cluster-guide/assets/142145515/61ded8c2-74d0-4f6d-9bb4-eacd9158c134">
3，该操作在同一台电脑上用其他人账号复现可以登录。
4，参考了问题 #6 ,尝试 konb restart 但是问题无法解决
<img width="649" alt="image" src="https://github.com/cihlab/fics-cluster-guide/assets/142145515/e3d92282-7894-4ede-9f04-9ecbda5ceb1f">

**Comment by zhutmost** [comment]
reset呢？

**Comment by liyjbruce** [comment]
> reset呢？

reset我还没尝试，因为不清楚reset会对当前环境有哪些影响？
比如socrates软件的正常运行需要下载了一些库，但是现在我在环境已经没有sudo 的权限，无法下载任何东西，我担心reset后，所有环境都被重置，然后也没有sudo权限，导致无法运行。

**Comment by zhutmost** [comment]
你说的很有道理。看看其他人咋解决吧。。。

**Comment by llfl** [comment]
1. 首先连接不上是cloud-mgmt网络转发的问题，因此knob上的所有数据不会有影响
2. 网络无法转发的原因是昨晚清理cloud-mgmt时，把管理ssh转发的数据库进程也清掉了，导致无法正常转发
3. 当前ssh转发数据库已恢复，问题应该是已经解决了

**Comment by liyjbruce** [comment]
> 1. 首先连接不上是cloud-mgmt网络转发的问题，因此knob上的所有数据不会有影响
> 2. 网络无法转发的原因是昨晚清理cloud-mgmt时，把管理ssh转发的数据库进程也清掉了，导致无法正常转发
> 3. 当前ssh转发数据库已恢复，问题应该是已经解决了

我重新尝试了一下，发现我依然连接不上vnc，如图，我的操作和之前相同，不知道是哪里出了问题
<img width="838" alt="image" src="https://github.com/cihlab/fics-cluster-guide/assets/142145515/ab816ec9-fb26-4d31-940d-6bd2ffd6533c">
