### ISSUE TITLE
Metis和Redhawk都没有license

### ISSUE THREAD

**Issue by ZexingChen** [cihlab/fics-cluster-guide#28]
Metis打开显示没有license，但王运正茂用同样的指令可以打开
![33841795ae5c3382e813ef652432997](https://github.com/user-attachments/assets/7103158b-a453-409b-96d9-5a76186af950)
![344dc7f9c2aaad0f2386b8dea426761](https://github.com/user-attachments/assets/c9c9bc07-2afa-435e-9090-ed77f8b985d7)

redhawk无法打开，显示没有license
![2f0e6e12ffb9a0f7cf932a488034217](https://github.com/user-attachments/assets/e152d9b8-dd98-4468-9add-a9d8d87dc1c7)

**Comment by llfl** [comment]
1. metis可能是你的home目录环境有问题
2. redhaw 你的打开方式不对
![image](https://github.com/user-attachments/assets/62e35a25-2592-462e-bd7d-7a4e55703a85)
