### ISSUE TITLE
可否安装一个新版本的calibre？

### ISSUE THREAD

**Issue by Acat-Wang** [cihlab/fics-cluster-guide#29]
目前的calibre版本有一些旧，有一些比较新的DRC文件跑不起来，DRC文件的文档表示支持v2022.1_36.16版本的calibre，能否安装一个v2022.1_36.16或更新版本的calibre？（麻烦的话就算了，旧的DRC文件也能凑合用用）

**Comment by zhutmost** [comment]
有安装软件么

**Comment by llfl** [comment]
找个能跑起来的可以帮你装上

**Comment by Acat-Wang** [comment]
在网上下了一个压缩包放在了/lamport/shared/acatwang/calibre_2022

**Comment by llfl** [comment]
![image](https://github.com/user-attachments/assets/223294f0-a4fe-49d3-85f2-7b6474b06687)
done

**Comment by Acat-Wang** [comment]
测试了打开layout/运行DRC/嵌入到virtuoso等操作，目前运行良好，感谢！
