### ISSUE TITLE
更改shell失败

### ISSUE THREAD

**Issue by ooooooooya** [cihlab/fics-cluster-guide#3]
初始shell是**bash**，但是我想把默认改成**zsh**。所以我发了邮件，收到了如下回复
<img width="277" alt="Snipaste_2023-10-25_23-07-36" src="https://github.com/cihlab/fics-cluster-guide/assets/30546437/005a47a1-b3d9-4dff-960a-c2c97416673f">

但是我重新上服务器，发现默认还是**bash**。
但是我重新登录服务器的时候CEDSA key好像是更新了？
<img width="575" alt="image" src="https://github.com/cihlab/fics-cluster-guide/assets/30546437/6adb6838-7dd5-4ff3-b074-bfbee92c81fd">

**Comment by zhutmost** [comment]
@ooooooooya  @llfl  这个问题解决了吗？

**Comment by llfl** [comment]
近期可以再试下？

**Comment by zhutmost** [comment]
鉴于issue不再活跃，我将它close掉了。
