### ISSUE TITLE
希望能更新一下iwave版本，安装包已经下载到服务器了

### ISSUE THREAD

**Issue by Acat-Wang** [cihlab/fics-cluster-guide#31]
旧版本有点bug影响使用，新版本安装包路径：/lamport/shared/acatwang/iWaveIC_2024.06.tmp_linux-x86_64-el6_20240705.tar

**Comment by llfl** [comment]
done

**Comment by Acat-Wang** [comment]
> done
貌似miller上不能load新版本的iwave，但knob确实是能用的，能不能修复一下
![image](https://github.com/user-attachments/assets/4a00f805-8fb7-4cc4-acd9-215cf04d874b)
