### ISSUE TITLE
文件夹突然变成root，且没有读写权限

### ISSUE THREAD

**Issue by xiaoshou-zheng** [cihlab/fics-cluster-guide#33]
在makkapakka节点上训练的时候，突然lamport上的数据集文件夹没有权限了
数据集的目录为：
/lamport/makkapakka/jpzheng/sk
![image](https://github.com/user-attachments/assets/95ae1436-88e2-4b3a-a873-549c08c4b420)

**Comment by llfl** [comment]
done

**Comment by llfl** [comment]
done
