### ISSUE TITLE
GPU Profiling: does not have permission to access NVIDIA GPU Performance Counters on the target device

### ISSUE THREAD

**Issue by Wulizhou888** [cihlab/fics-cluster-guide#4]
尊敬的管理员您好，我近期在研究三维重建方向的课题，需要用到GPU集群进行训练以及性能分析（Profiling）。具体而言，需要使用Nsight Compute工具分析CUDA Kernel函数内各操作的计算与访存开销。然而，Nsight Compute工具需要访问GPU底层的硬件信息，如Performance Counter，这需要管理员的权限（针对418.43以上版本的Linux系统）。
Nivida官方说明书有提到，管理员权限下可以将Profiling的权限向普通用户打开。具体需要执行以下步骤：
1.在/etc/modprobe.d中创建一个扩展名为.conf的文件，其中包含：
“options nvidia NVreg_RestrictProfilingToAdminUsers=0”
2.可能需要reboot才能使改变产生效果
3.在某些系统上(或使用包管理器进行安装时)，在 /etc/modprobe.d 创建配置文件后，可能需要rebuild initrd（对于redhat系统，使用dracut --regenerate-all -f来rebuild initrd）

此外，管理员还可临时地为普通用户开放权限，步骤如下：
1.为了能够在内核模块中配置对应的key，需要先停止窗口管理器并卸载所有NVIDIA内核模块：
(1) 停止窗口管理器：systemctl isolate multi-user
(2) 卸载NVIDIA内核模块：modprobe -rf nvidia_uvm nvidia_drm nvidia_modeset nvidia-vgpu-vfio nvidia
2.开放权限：modprobe nvidia NVreg_RestrictProfilingToAdminUsers=0
3.重启窗口管理器：systemctl isolate graphical
具体参见网页：[NVIDIA Development Tools Solutions - | NVIDIA Developer](https://developer.nvidia.com/nvidia-development-tools-solutions-err_nvgpuctrperm-permission-issue-performance-counters)

感谢您的关注！

**Comment by zhutmost** [comment]
@llfl 我确认过了，需求是正当的。但是不确定会不会引起其他人不必要的bug和风险。

// wlz你这个开issue写的也太书面了 。。。

**Comment by llfl** [comment]
了解了，看起来透出非管理员权限需要在nvidia驱动上加上个参数。Nvidia说明书上确定是只要加了这个参数就可以么？

**Comment by Wulizhou888** [comment]
应该是的，官网是这么写的
![image](https://github.com/cihlab/fics-cluster-guide/assets/63011284/b67addd6-e5a8-4954-b673-1a1a540be185)

**Comment by llfl** [comment]
操作需要所有gpu任务停止并重启驱动，makkapakka04 已经设置为draining，等makkapakka04上所有任务排空后操作

**Comment by llfl** [comment]
makkapakka04的nvidia 驱动已经设置为NVreg_RestrictProfilingToAdminUsers=0

**Comment by Wulizhou888** [comment]
管理员您好，我在输入 srun -p makkapakka --nodelist=makkapakka04 which ncu 命令后发现有如下报错，似乎makkapakka04节点无法识别 /capsule/home/lizhouwu 的路径：
![3683b4fd3cb7bbf7fb6624ee2e7ad8a](https://github.com/cihlab/fics-cluster-guide/assets/63011284/473ab278-e20c-4bc8-b66a-a00f867adc8d)
我尝试过其他节点，如makkapakka03，它是可以识别出ncu工具的安装路径的：
![3683b4fd3cb7bbf7fb6624ee2e7ad8a](https://github.com/cihlab/fics-cluster-guide/assets/63011284/14a5c706-3a79-4b26-9e15-b2c087e81ca4)
劳烦您帮忙排查一下原因，谢谢！

**Comment by Wulizhou888** [comment]
管理员您好，我在输入 srun -p makkapakka --nodelist=makkapakka04 which ncu 命令后发现有如下报错，似乎makkapakka04节点无法识别 /capsule/home/lizhouwu 的路径：
![image](https://github.com/cihlab/fics-cluster-guide/assets/63011284/a9ff2299-66b7-4249-a014-333d50248ce7)
我尝试过其他节点，如makkapakka03，它是可以识别出ncu工具的安装路径的：
![image](https://github.com/cihlab/fics-cluster-guide/assets/63011284/67329305-f049-4ded-8db2-0746bcb2bb17)
劳烦您帮忙排查一下原因，谢谢！

**Comment by llfl** [comment]
看起来是东西没source全

**Comment by Wulizhou888** [comment]
> 看起来是你自己没把东西source全

我将 ls /capsule 命令提交到 makkapakka04和03节点，03是能识别路径的，但是04没法识别：
![image](https://github.com/cihlab/fics-cluster-guide/assets/63011284/99321322-48d3-4a15-8406-bec832dd531a)

**Comment by Wulizhou888** [comment]
> > 看起来是你自己没把东西source全
> 
> 我将 ls /capsule 命令提交到 makkapakka04和03节点，03是能识别路径的，但是04没法识别： ![image](https://private-user-images.githubusercontent.com/63011284/293572365-99321322-48d3-4a15-8406-bec832dd531a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwOTIzMDAsIm5iZiI6MTcwNDA5MjAwMCwicGF0aCI6Ii82MzAxMTI4NC8yOTM1NzIzNjUtOTkzMjEzMjItNDhkMy00YTE1LTg0MDYtYmVjODMyZGQ1MzFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA2NTMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZDdiZmI0MzAzYTkyMTJlMjU4Y2E2YzI0NzYwZDM4NjUwZjBiZDU3YjMxYmNkODNjOGJmNzFlNTAwYmEwYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jwR6Df5Zz7SgfIQ_p7lWd9Kf9agySstG_ofM3GflULI)

似乎04节点没法看到capsule路径下的目录

**Comment by llfl** [comment]
oh I see 现在应该解决了

**Comment by Wulizhou888** [comment]
问题已解决，感谢！
