### ISSUE TITLE
把薪金博服务器的aether迁移到FICS服务器上

### ISSUE THREAD

**Issue by Acat-Wang** [cihlab/fics-cluster-guide#5]
在FICS服务器安装eather
迁移license
用于大规模电路仿真

**Comment by Acat-Wang** [comment]
安装包大约是薪金博服务器上的/EDA/EmpyreanInstallFiles文件夹里面的这个？
license之前是手动更新，然后通过运行/EDA/autolicense.sh这个脚本来认证的，如果迁移到FICS服务器还需要这个脚本吗

**Comment by llfl** [comment]
<img width="1003" alt="image" src="https://github.com/cihlab/fics-cluster-guide/assets/10126413/dec6c74e-9c89-42ea-b878-caaac8d1f0d9">
done

**Comment by llfl** [comment]
> 安装包大约是薪金博服务器上的/EDA/EmpyreanInstallFiles文件夹里面的这个？ license之前是手动更新，然后通过运行/EDA/autolicense.sh这个脚本来认证的，如果迁移到FICS服务器还需要这个脚本吗

auto license就是我写的，这个脚本已经不适用fics了
