### ISSUE TITLE
VNC连接失败问题

### ISSUE THREAD

**Issue by jingxi-chen** [cihlab/fics-cluster-guide#6]
管理员老师您好，我尝试使用VNC连接服务器，但是遇到了下方描述的问题：
1. 我按照ssh端口转发的登录方式登录服务器之后，输入“vnc”指令发现当前状态为未开启。随后我进行了vnc密码的设置，然后打开了vnc。
2. 在vnc打开后，我又执行了指令“vnc”，**发现状态还是未开启**。
3. 手动关闭vnc，再重新打开，依旧会出现2中的问题。
4. 这种情况下，在vnc viewer中尝试连接会出现“channel 3: open failed: connect failed: Connection refused”的错误。
整体情况如下图所示：
![屏幕截图 2024-01-16 131021](https://github.com/cihlab/fics-cluster-guide/assets/143076516/7941f16d-2a4c-42d4-bc8b-778f83303242)

**Comment by zhutmost** [comment]
@llfl ，你要不要关于VNC问题出一个通用的solution/文档？

**Comment by llfl** [comment]
vnc restart即可

**Comment by jingxi-chen** [comment]
目前能连接了

> vnc restart即可
