### ISSUE TITLE
miller相关问题

### ISSUE THREAD

**Issue by Acat-Wang** [cihlab/fics-cluster-guide#7]
1.aether需要更新版本，2019太旧了，解压后的安装包我放在了/capsule/share/acatwang/aether/aether_2023.12_linux-x86_64-el6_20240103

2.如果要用virtuoso调用alps，需要在miller运行virtuoso，但我尝试在load ic618之后运行virtuoso，无法正常启动
具体表现为会先出现一个图形界面的轮廓（只有轮廓，没有文字和按钮），然后在virtuoso加载完成之前图形界面的轮廓就消失了，运行日志如图
![image](https://github.com/cihlab/fics-cluster-guide/assets/46415662/ddc0951c-ebe9-44f2-8d2a-82c185c152b2)

**Comment by llfl** [comment]
aether 2023 install done

**Comment by llfl** [comment]
virtuoso seem work fine now

**Comment by zhutmost** [comment]
@Acat-Wang Please help test
