### ISSUE TITLE
运行verdi显示can't open display

### ISSUE THREAD

**Issue by SuchangHuang** [cihlab/fics-cluster-guide#9]
运行verdi会报错，显示can't open display，google了一下有说是DISPLAY变量没设置好的，有说是X11 forwarding出问题的，尝试了一下都没有解决
![error](https://github.com/cihlab/fics-cluster-guide/assets/144028535/2fe5c2c6-6bf0-43f2-ac05-1de46b71d626)

**Comment by llfl** [comment]
通过knob解决
